allowBuilds:
  "@journeyapps/wa-sqlite": true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true

onlyBuiltDependencies:
  - "@journeyapps/wa-sqlite"
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
