/* eslint-disable unicorn/no-null -- createThemeContract requires null placeholders */
import { createThemeContract } from "@vanilla-extract/css";

export const vars = createThemeContract({
  color: {
    bg: {
      page: null,
      surface: null,
      surfaceAlt: null,
      inverse: null,
    },
    fg: {
      default: null,
      muted: null,
      faint: null,
      onAccent: null,
      onInverse: null,
      onInverseMuted: null,
    },
    border: {
      default: null,
      strong: null,
      subtle: null,
      control: null,
      inverse: null,
      hover: null,
      hoverStrong: null,
    },
    accent: {
      default: null,
      hover: null,
      fg: null,
      soft: null,
      softBorder: null,
      softFg: null,
    },
    surface: {
      tier1: { bg: null, border: null },
      tier2: { bg: null, border: null },
      tier3: { bg: null, border: null },
      inverse: { bg: null, border: null, fg: null, muted: null },
    },
    tag: {
      user: { bg: null, border: null, fg: null },
    },
    status: {
      positiveBg: null,
      positiveBorder: null,
      positiveFg: null,
      positiveIcon: null,
      neutralBg: null,
      neutralBorder: null,
      neutralFg: null,
      negativeBg: null,
      negativeBorder: null,
      negativeFg: null,
      errorFg: null,
      loadingFg: null,
      readyFg: null,
    },
    skeleton: {
      shade1: null,
      shade2: null,
      shade3: null,
      shade4: null,
    },
  },
  space: {
    "0": null,
    "1": null,
    "2": null,
    "3": null,
    "4": null,
    "5": null,
    "6": null,
    "7": null,
    "8": null,
    "10": null,
    "12": null,
    "14": null,
    "16": null,
    "20": null,
    "24": null,
    "32": null,
    "40": null,
    "48": null,
    "64": null,
    "96": null,
  },
  radii: {
    none: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    full: null,
    circle: null,
  },
  size: {
    controlSm: null,
    controlMd: null,
    controlLg: null,
    statusBar: null,
    contentColumn: null,
    popup: null,
    inputMin: null,
    inputFocused: null,
  },
  font: {
    family: {
      serif: null,
      mono: null,
    },
    size: {
      "2xs": null,
      xs: null,
      sm: null,
      md: null,
      lg: null,
      xl: null,
      "2xl": null,
      "3xl": null,
      "4xl": null,
      display: null,
    },
    weight: {
      regular: null,
      medium: null,
    },
    leading: {
      none: null,
      tight: null,
      snug: null,
      normal: null,
      loose: null,
    },
    tracking: {
      tight: null,
      normal: null,
      wide: null,
    },
  },
  shadow: {
    card: null,
    cardInverse: null,
    popup: null,
  },
  zIndex: {
    statusBar: null,
    popup: null,
  },
});
