/**
 * CSS reset — modern-normalize v3.0.1 + Tailwind preflight
 * This port is generated by Claude Code
 *
 * Sources:
 *   https://github.com/sindresorhus/modern-normalize
 *   https://github.com/tailwindlabs/tailwindcss/blob/main/packages/tailwindcss/preflight.css
 *
 * Strategy: modern-normalize first (cross-browser consistency fixes),
 * preflight additions on top (aggressive opinionated resets). Where they
 * conflict, preflight wins — it is the superset and more modern.
 * All rules live inside the `reset` layer so base/components/utilities
 * can always override without specificity fights.
 */
// oxlint-disable no-inline-comments sort-keys max-lines

import { globalStyle } from "@vanilla-extract/css";

// Import first — establishes layer declaration order
import { reset } from "./layers.css";

// ─── Document ────────────────────────────────────────────────────

/**
 * [normalize] Use a better box model.
 * [preflight] Reset borders to 0 width, solid style, current color.
 *   Means you can add a border by setting `border-width` alone,
 *   without also setting style and color every time.
 */
globalStyle("*, ::before, ::after", {
  "@layer": {
    [reset]: {
      borderColor: "currentcolor",
      borderStyle: "solid",
      borderWidth: 0,
      boxSizing: "border-box",
    },
  },
});

/**
 * [normalize] 1. Improve consistency of default fonts in all browsers.
 *                https://github.com/sindresorhus/modern-normalize/issues/3
 *             2. Correct the line height in all browsers.
 *             3. Prevent adjustments of font size after orientation changes in iOS.
 *             4. Use a more readable tab size (opinionated).
 * [preflight] 5. Override line-height to 1.5 — normalize uses 1.15 which is
 *                too tight. Preflight's 1.5 matches browser default and is
 *                better for readability.
 *             6. Inherit font-feature-settings and font-variation-settings from
 *                user agent / OS preferences.
 *             7. Remove iOS tap highlight — prevents the grey flash on tap.
 */
globalStyle("html", {
  "@layer": {
    [reset]: {
      fontFamily:
        "system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji'", // 1
      lineHeight: 1.5, // 2 → overridden to 1.5 by preflight (5)
      WebkitTextSizeAdjust: "100%", // 3
      tabSize: 4, // 4
      fontFeatureSettings: "normal", // 6
      fontVariationSettings: "normal", // 6
      WebkitTapHighlightColor: "transparent", // 7
    },
  },
});

// ─── Sections ────────────────────────────────────────────────────

// [normalize] Remove the margin in all browsers.
globalStyle("body", {
  "@layer": {
    [reset]: {
      margin: 0,
    },
  },
});

// ─── Text-level semantics ─────────────────────────────────────────

// [normalize] Add the correct font weight in Chrome and Safari.
globalStyle("b, strong", {
  "@layer": {
    [reset]: {
      fontWeight: "bolder",
    },
  },
});

/**
 * [normalize] 1. Improve consistency of default fonts in all browsers.
 *                https://github.com/sindresorhus/modern-normalize/issues/3
 *             2. Correct the odd 'em' font sizing in all browsers.
 */
globalStyle("code, kbd, samp, pre", {
  "@layer": {
    [reset]: {
      fontFamily: "ui-monospace, SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace", // 1
      fontSize: "1em", // 2
    },
  },
});

// [normalize] Add the correct font size in all browsers.
globalStyle("small", {
  "@layer": {
    [reset]: {
      fontSize: "80%",
    },
  },
});

// [normalize] Prevent 'sub' and 'sup' from affecting the line height in all browsers.
globalStyle("sub, sup", {
  "@layer": {
    [reset]: {
      fontSize: "75%",
      lineHeight: 0,
      position: "relative",
      verticalAlign: "baseline",
    },
  },
});

globalStyle("sub", {
  "@layer": {
    [reset]: {
      bottom: "-0.25em",
    },
  },
});

globalStyle("sup", {
  "@layer": {
    [reset]: {
      top: "-0.5em",
    },
  },
});

/**
 * [preflight] Strip heading font size and weight.
 *   Browser UA gives h1–h6 progressively smaller sizes and bold weight.
 *   Resetting to `inherit` makes headings unstyled by default — you opt in
 *   to heading styles explicitly in your base/components layer.
 */
globalStyle("h1, h2, h3, h4, h5, h6", {
  "@layer": {
    [reset]: {
      fontSize: "inherit",
      fontWeight: "inherit",
    },
  },
});

/**
 * [preflight] Reset anchor styles.
 *   Browsers style `<a>` with blue + underline. Resetting to inherit means
 *   links look like surrounding text until you style them intentionally.
 *   Prevents unstyled links from bleeding through in unexpected places.
 */
globalStyle("a", {
  "@layer": {
    [reset]: {
      color: "inherit",
      textDecoration: "inherit",
    },
  },
});

// ─── Tabular data ─────────────────────────────────────────────────

/**
 * [normalize] Correct table border color inheritance in Chrome and Safari.
 *   https://issues.chromium.org/issues/40615503
 *   https://bugs.webkit.org/show_bug.cgi?id=195016
 * [preflight] Also reset text-indent and collapse borders.
 *   Chrome/Safari indent table text; collapse removes double-border gaps.
 */
globalStyle("table", {
  "@layer": {
    [reset]: {
      borderCollapse: "collapse",
      borderColor: "currentcolor",
      textIndent: 0,
    },
  },
});

// ─── Lists ───────────────────────────────────────────────────────

/**
 * [preflight] Remove list styles, margin, and padding from ol/ul/menu.
 *   UA renders bullets/numbers and indentation by default. Resetting here
 *   means all lists are unstyled — add bullets back deliberately in base layer.
 */
globalStyle("ol, ul, menu", {
  "@layer": {
    [reset]: {
      listStyle: "none",
      margin: 0,
      padding: 0,
    },
  },
});

// ─── Embedded content ─────────────────────────────────────────────

/**
 * [preflight] Make media elements block-level and middle-aligned.
 *   Inline images get a gap below them (descender space) by default.
 *   `display: block` eliminates that. Covers all replaced elements.
 */
globalStyle("img, svg, video, canvas, audio, iframe, embed, object", {
  "@layer": {
    [reset]: {
      display: "block",
      verticalAlign: "middle",
    },
  },
});

/**
 * [preflight] Constrain images/video to their container.
 *   `max-width: 100%` prevents overflow. `height: auto` preserves aspect ratio
 *   when width is constrained.
 */
globalStyle("img, video", {
  "@layer": {
    [reset]: {
      height: "auto",
      maxWidth: "100%",
    },
  },
});

// ─── Forms ───────────────────────────────────────────────────────

/**
 * [normalize] 1. Change the font styles in all browsers.
 *             2. Remove the margin in Firefox and Safari.
 * [preflight] 3. Also reset padding and line-height to inherit,
 *                and add font-weight: inherit.
 *             4. ::file-selector-button — modern standard selector
 *                (replaces ::-webkit-file-upload-button for non-webkit).
 */
globalStyle("button, input, select, optgroup, textarea, ::file-selector-button", {
  "@layer": {
    [reset]: {
      fontFamily: "inherit", // 1
      fontSize: "100%", // 1
      fontWeight: "inherit", // 3
      lineHeight: "inherit", // 3
      margin: 0, // 2
      padding: 0, // 3
    },
  },
});

// [normalize] Correct the inability to style clickable types in iOS and Safari.
globalStyle("button, [type='button'], [type='reset'], [type='submit']", {
  "@layer": {
    [reset]: {
      WebkitAppearance: "button",
    },
  },
});

/**
 * [preflight] Restore optgroup font-weight inside select.
 *   The broad reset above strips bold from optgroup labels — put it back
 *   so grouped options remain visually distinguishable.
 */
globalStyle("select optgroup", {
  "@layer": {
    [reset]: {
      fontWeight: "bolder",
    },
  },
});

/**
 * [preflight] Restore indent on options inside optgroups.
 *   Resetting padding on optgroup above can collapse option indentation
 *   in some browsers. Explicitly restore it.
 */
globalStyle("select optgroup option", {
  "@layer": {
    [reset]: {
      paddingInlineStart: "20px",
    },
  },
});

// [normalize] Remove the padding so developers are not caught out when they
// Zero out 'fieldset' elements in all browsers.
globalStyle("legend", {
  "@layer": {
    [reset]: {
      padding: 0,
    },
  },
});

// [normalize] Add the correct vertical alignment in Chrome and Firefox.
globalStyle("progress", {
  "@layer": {
    [reset]: {
      verticalAlign: "baseline",
    },
  },
});

// [normalize] Correct the cursor style of increment/decrement buttons in Safari.
globalStyle("::-webkit-inner-spin-button, ::-webkit-outer-spin-button", {
  "@layer": {
    [reset]: {
      height: "auto",
    },
  },
});

/**
 * [normalize] 1. Correct the odd appearance in Chrome and Safari.
 *             2. Correct the outline style in Safari.
 */
globalStyle("[type='search']", {
  "@layer": {
    [reset]: {
      WebkitAppearance: "textfield", // 1
      outlineOffset: "-2px", // 2
    },
  },
});

// [normalize] Remove the inner padding in Chrome and Safari on macOS.
globalStyle("::-webkit-search-decoration", {
  "@layer": {
    [reset]: {
      WebkitAppearance: "none",
    },
  },
});

/**
 * [normalize/preflight] Style file upload buttons.
 *   ::-webkit-file-upload-button — legacy webkit pseudo-element.
 *   ::file-selector-button — modern standard (handled in the broad reset above).
 *   1. Correct the inability to style clickable types in iOS and Safari.
 *   2. Change font properties to 'inherit' in Safari.
 */
globalStyle("::-webkit-file-upload-button", {
  "@layer": {
    [reset]: {
      WebkitAppearance: "button", // 1
      font: "inherit", // 2
    },
  },
});

/**
 * [preflight] Add spacing after file selector button.
 *   Prevents button from touching the filename text.
 */
globalStyle("::file-selector-button", {
  "@layer": {
    [reset]: {
      marginInlineEnd: "0.5rem",
    },
  },
});

/**
 * [preflight] Reset placeholder opacity.
 *   Firefox renders placeholder at reduced opacity by default.
 *   Setting to 1 lets you control placeholder color purely via `color`.
 */
globalStyle("::placeholder", {
  "@layer": {
    [reset]: {
      opacity: 1,
    },
  },
});

/**
 * [preflight] Restrict textarea resize to vertical only.
 *   Horizontal resize breaks layouts. Users can still resize vertically
 *   to reveal more content.
 */
globalStyle("textarea", {
  "@layer": {
    [reset]: {
      resize: "vertical",
    },
  },
});

// ─── Interactive ─────────────────────────────────────────────────

// [normalize] Add the correct display in Chrome and Safari.
globalStyle("summary", {
  "@layer": {
    [reset]: {
      display: "list-item",
    },
  },
});

/**
 * [preflight] Enforce `display: none` on [hidden].
 *   Some CSS resets or frameworks accidentally make `[hidden]` visible.
 *   `:where()` keeps specificity at 0 so it can still be overridden.
 */
globalStyle("[hidden]:where(:not([hidden='until-found']))", {
  "@layer": {
    [reset]: {
      display: "none",
    },
  },
});
